### ISSUE TITLE
Query `parameters` containing `.` generate invalid code

### ISSUE THREAD

**Issue by micolous** [sennder/python-client-generator#30]
Example of a parameter with `.` which breaks the generator (as YAML-formatted OAS):

```yaml
/example:
  get:
    parameters:
      - in: query
        name: foo.bar
        schema:
          format: int32
          type: integer
      - in: query
        name: foo.baz
        schema:
          format: int32
          type: integer
```

The generator builds the API method as:

```python
async def example(
  self,
  foo.bar -> int,
  foo.baz -> int,
  **kwargs: Any
) -> ExampleResponse:
  _query_params = {
    "foo.bar": foo.bar,
    "foo.baz": foo.baz,
  }
  # ...
```

OpenAPI Generator replaces `.` with `_`, so the field name becomes `foo_bar`.
